version: '3'
services:
  flyway:
    image: flyway/flyway:9.20-alpine
    command: -url=jdbc:postgresql://db:5432/postgres  -user=postgres -password=postgres -connectRetries=2 info
    volumes:
      - ./database-migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: postgres:alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres