FROM python:3.10

ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY ./requirements.txt /app/requirements.txt

RUN pip install --upgrade pip

RUN Pip install --no-cache-dir --upgrade -r requirements.txt

COPY /app /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]