default_context:
  project_name: 'devolinkbackend'
  project_slug: 'devolinkbackend'
  domain_main: 'devolinkbackend.com'
  domain_staging: 'stag.devolinkbackend.com'
  docker_swarm_stack_name_main: 'devolinkbackend-com'
  docker_swarm_stack_name_staging: 'stag-devolinkbackend-com'
  secret_key: 'edp'
  first_superuser: 'admin@devolinkbackend.com'
  first_superuser_password: 'superedp'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.devolinkbackend.com", "https://stag.devolinkbackend.com", "https://devolinkbackend.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@devolinkbackend.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'devolinkbackend.com'
  traefik_constraint_tag_staging: 'stag.devolinkbackend.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:superedp'
  sentry_dsn: ''
  docker_image_prefix: 'backend'
  docker_image_backend: 'backend_back'
  docker_image_celeryworker: 'backendceleryworker'
  docker_image_frontend: 'backendfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
