version: '3'

services:
  backend:
    image: cycleflow_backend
    container_name: cycleflow_backend
    build:
      context: ./cycleflow/backend
      dockerfile: cycleflow-backend.dockerfile
    volumes:
      - .:/code
    ports:
      - 3000:3000
    # depends_on:
    #   - myapp-database
    # links:
    #   - myapp-database
    # environment:
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: ml7H0G8H5j!
    #   POSTGRES_SERVER: postgres_db
    #   POSTGRES_PORT: "5432"
    #   POSTGRES_DB: metrics_database
    #   JWT_SECRET_KEY: test
    #   JWT_REFRESH_SECRET_KEY: test
