# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature/*

# pool:
#   vmImage: ubuntu-latest

pool: 
  vmImage: windows-2022

# pool: 
#   name: default
#   demands:
#     - agent.name -equals mydockeragent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: PowerShell@2
  inputs:
    filePath: 'build/build_db_nuspec.ps1'
    arguments: 'betcycle-migrations'
  displayName: 'build and replace'

- task: PowerShell@2
  inputs:
    filePath: 'build/build_db_nuget_pack.ps1'
    arguments: 'betcycle-migrations $(Build.BuildNumber)'
  displayName: 'create pack'

- task: PowerShell@2
  inputs:
    filePath: 'build/build_db_nuget_push.ps1'
    arguments: 'betcycle-migrations $(Build.BuildNumber)'
  displayName: 'publish pack'