name: backend docker build

on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - 'backend/**'
      - '.github/workflows/backend-docker-build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-docker-build.yml'

env:
  VERSION_MAJOR: 0
  VERSION_MINOR: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t betcycle-backend:${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{ github.run_number }} ./backend
