name: betcycle-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #run: docker build . --file ./betcycle/backend/Dockerfile --tag betcycle-backend:$(date +%s)
      run: docker build --tag betcycle-backend:$(date +%s) ./betcycle/backend


    - name: Log in to Docker Hub
      run: docker loging -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

